runtime: python311

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /google13d98156732d1c0e\.html
  static_files: google13d98156732d1c0e.html
  upload: google13d98156732d1c0e\.html

- url: /site
  static_dir: site

